const {chromium}=require('C:/Users/dyw/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert/strict'),out='D:/AI语言训练/mouth_teacher/work/v3';
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=d3d11']});const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[],report={};
p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/THREE|WebGL|shader/i.test(m.text()))errors.push(m.text());});
try{await p.goto('http://127.0.0.1:8787/');await p.waitForFunction(()=>window.teacher?.ready,null,{timeout:60000});await p.screenshot({path:out+'/screens/shared-tongue-normal.png'});await p.locator('#oral-toggle').click();
for(const name of ['front','retro','tip']){await p.locator(`[data-tongue=${name}]`).click();await p.waitForTimeout(1990);await p.locator('#oral-hold').click();await p.waitForTimeout(100);report[name]=await p.evaluate(()=>({points:teacher.diagnostics.oral,controls:teacher.controls}));await p.screenshot({path:out+'/screens/'+name+'-calibrated.png'});}
assert(report.retro.points.tipSurface[1]>report.front.points.tipSurface[1]+.01,'retroflex tip must retract');assert(report.retro.points.tipSurface[2]>report.front.points.tipSurface[2]+.02,'retroflex tip must rise');
const text='四是四，十是十。';await p.locator('#text').fill(text);const response=p.waitForResponse(r=>r.url().endsWith('/api/speech')&&r.request().method()==='POST');await p.locator('#observe').click();const packet=await (await response).json();assert(!packet.error,packet.error);fs.writeFileSync(out+'/sibilant-packet.json',JSON.stringify(packet));
await p.waitForFunction(()=>teacher.state==='playing',null,{timeout:60000});report.spoken={s:{retro:0,groove:0},sh:{retro:0,groove:0}};
for(let i=0;i<500;i++){await p.waitForTimeout(25);const x=await p.evaluate(()=>({state:teacher.state,time:teacher.audioTime,retro:teacher.controls.tongueRetroflex||0,groove:teacher.controls.tongueGroove||0}));if(x.state==='idle')break;const unit=packet.syllables.find(s=>x.time>=s.time&&x.time<s.end);if(unit&&report.spoken[unit.initial]){const v=report.spoken[unit.initial];v.retro=Math.max(v.retro,x.retro);v.groove=Math.max(v.groove,x.groove);}}
assert.equal(report.spoken.s.retro,0);assert(report.spoken.s.groove>.6);assert(report.spoken.sh.retro>.7);assert.deepEqual(errors,[]);report.errors=errors;report.passed=true;console.log(JSON.stringify({spoken:report.spoken,passed:report.passed}));
}finally{fs.writeFileSync(out+'/sibilant-acceptance.json',JSON.stringify(report,null,2));await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
